services:
  mariadb:
    image: mariadb
    container_name: mariadba7
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      MARIADB_USER: ${SQL_USER}
      MARIADB_PASSWORD: ${SQL_PASSWORD}
      MARIADB_DATABASE: ${SQL_DATABASE}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./Zapatos.sql:/docker-entrypoint-initdb.d/Zapatos.sql
    user: mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmina7
    environment:
      - PMA_HOST=mariadb
    ports:
      - 7007:80
    depends_on:
      - mariadb
    restart: unless-stopped
  python:
    build: ./api
    # imagen/python:${TAG_IMG}
    container_name: pythona7
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
      HOST: ${HOST}
    depends_on:
      - mariadb
    restart: unless-stopped
  apache:
    container_name: apachea7
    build: ./apache #./waf/ en un futuro
    # imagen/WAF:${TAG_WAF}
    ports:
      - $EXPOSED_PORT_APACHE:80
    depends_on:
      - python
    links:
      - python
    restart: unless-stopped
volumes:
  mariadb_data:
