env:
  contexts:
    - name: "AppContext"
      urls:
        #- "http://10.227.87.9:30607"
        - "http://localhost:8080"
      includePaths:
        #- "http://10.227.87.9:30607/.*"
        - "http://localhost:8080/.*"
      authentication:
        method: json
        parameters:
          #loginPageUrl: "http://10.227.87.9:30607/index.html"
          loginPageUrl: "http://localhost:8080/index.html"
          #loginRequestUrl: "http://10.227.87.9:30607/api/usuarios/login"
          loginRequestUrl: "http://localhost:8080/api/usuarios/login"
          loginRequestBody: '{"username":"{%username%}","password":"{%password%}"}'
      users:
        - name: "zap_user"
          credentials:
            username: "root"
            password: "1234"
  parameters:
    failOnError: false

jobs:
  - type: spider
    parameters:
      context: "AppContext"
      user: "zap_user"

  - type: activeScan
    parameters:
      context: "AppContext"
      user: "zap_user"

  - type: report
    parameters:
      template: "traditional-html"
      reportFile: "zap-report.html"

