env:
  contexts:
    - name: "AppContext"
      urls:
        #- "http://10.227.87.250:6600"
        - "http://172.17.0.1:8080"
      includePaths:
        #- "http://10.227.87.250:6600"
        - "http://172.17.0.1:8080/.*"
      #authentication:
        #method: form
        #parameters:
          #loginPageUrl: "http://10.227.87.250:6600/login"
          #loginRequestUrl: "http://10.227.87.250:6600/login"
          #loginRequestBody: "username={%username%}&password={%password%}"
      #users:
        #1- name: "usuario1"
          #credentials:
            #username: "admin"
            #password: "1234"
  parameters:
    #failOnError: true
    failOnError: false

jobs:
  - type: spider
    parameters:
      context: "AppContext"
      #user: "usuario1"

  - type: activeScan
    parameters:
      context: "AppContext"
      #user: "usuario1"

  - type: report
    parameters:
      template: "traditional-html"
      reportFile: "zap-report.html"

