apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache_waf
  namespace: grupo7a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache_waf
  template:
    metadata:
      labels:
        app: apache_waf
    spec:
      containers:
        - name: apache
#          image: zoltar238/kubeapache:1.0
          image: fmoha21/pps-apache:${FINAL_IMAGE_TAG_WAF}
          ports:
            - containerPort: 80

