apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: grupo7a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
#      securityContext:
#        fsGroup: 1001
      containers:
        - name: mariadb
          #image: mariadb:11-ubi
          image: mariadb:10.5
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grupo7a-secret
                  key: SQL_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: grupo7a-secret
                  key: SQL_DATABASE
          envFrom:
            - secretRef:
                name: grupo7a-secret
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
            - name: mariadb-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: grupo7a-pvc
        - name: mariadb-init
          configMap:
            name: mariadb-initdb

