apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: grupoa7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:5.2.3
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mariadb
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: grupoa7-secret
                  key: DB_USERNAME
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grupoa7-secret
                  key: DB_PASSWORD
            - name: PMA_PORT
              value: "3306"
