apiVersion: v1
kind: PersistentVolume
metadata:
  name: grupo7a-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Delete
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/grupo7a
#    path: /home/grupo7a/mnt/data/grupo7a
