apiVersion: v1
kind: PersistentVolume
metadata:
  name: grupoa7-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Delete
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/grupoa7
