apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grupo7a-pvc
  namespace: grupo7a
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
