apiVersion: v1
kind: Namespace
metadata:
  name: grupo7a

---

apiVersion: v1
kind: Secret
metadata:
  name: grupo7a-secret
  namespace: grupo7a
type: Opaque
data:

  SQL_ROOT_PASSWORD: ZXhhbXBsZQ==
  SQL_USER: YWdlbnRl
  SQL_PASSWORD: T3RyYUNsYXZl
  SQL_DATABASE: Y2liZXI=

  DB_USERNAME: cm9vdA==
  DB_PASSWORD: ZXhhbXBsZQ==
  DB_DATABASE: Y2liZXI=
  DB_HOST: bWFyaWFkYg==
  DB_PORT: MzMwNg==

  PORT: ODA4MA==
  HOST: MC4wLjAuMA==

