apiVersion: v1
kind: Namespace
metadata:
  name: grupo7a

---

apiVersion: v1
kind: Secret
metadata:
  name: grupo7a-secret
  namespace: grupo7a
type: Opaque
data:
  # Database credentials
  SQL_ROOT_PASSWORD: cm9vdA==  # root
  SQL_USER: YWRtaW4=  # admin
  SQL_PASSWORD: YWRtaW4=  # admin
  SQL_DATABASE: Y2liZXJBNw==  # ciberA7

  # API database access
  DB_USERNAME: YWRtaW4=  # admin
  DB_PASSWORD: YWRtaW4=  # admin
  DB_DATABASE: Y2liZXJBNw==  # ciberA7
  DB_HOST: bWFyaWFkYg==  # mariadb
  DB_PORT: MzMwNg==  # 3306

  # Flask configuration
  PORT: ODA4MA==  # 8080
  HOST: MC4wLjAuMA==  # 0.0.0.0
  SECRET_KEY: c25lYWtlcnNob3BfYTdfZmxhc2tfc2VjcmV0X2tleV8yMDI2  # sneakershop_a7_flask_secret_key_2026
  WTF_CSRF_SECRET_KEY: Y3NyZl9zZWNyZXRfa2V5XzIwMjY=  # csrf_secret_key_2026
  PEPPER_KEY: cGVwcGVyX2tleV9zYWx0XzIwMjY=  # pepper_key_salt_2026

