ServerName localhost

LoadModule deflate_module /usr/local/apache2/modules/mod_deflate.so
LoadModule proxy_module /usr/local/apache2/modules/mod_proxy.so
LoadModule proxy_fcgi_module /usr/local/apache2/modules/mod_proxy_fcgi.so
LoadModule proxy_http_module /usr/local/apache2/modules/mod_proxy_http.so
LoadModule ssl_module /usr/local/apache2/modules/mod_ssl.so

Listen 443

<VirtualHost *:443>

    SSLEngine on
    SSLCertificateFile "/usr/local/apache2/certs/cert.pem"
    SSLCertificateKeyFile "/usr/local/apache2/certs/key.pem"

    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off

    ProxyPass /api/ https://python:8080/api/
    ProxyPassReverse /api/ https://python:8080/api/

    DocumentRoot /var/www/html/
    <Directory /var/www/html/>
        DirectoryIndex index.html
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    
    CustomLog /proc/self/fd/1 common
    ErrorLog /proc/self/fd/2
</VirtualHost>

