services:
  mariadb:
    image: mariadb
    container_name: mariadba7
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 0traClave
      MARIADB_DATABASE: ciber
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./Zapatos.sql:/docker-entrypoint-initdb.d/Zapatos.sql
    user: mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmina7
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - $EXPOSED_PORT_MYADMIN:80
    depends_on:
      - mariadb
  python:
    build: ./api
    container_name: pythona7
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: ciber
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    depends_on:
      - mariadb
    restart: unless-stopped
  apache-waf:
    container_name: apachea7
    build: ./apache #./waf/ en un futuro
    ports:
      - $EXPOSED_PORT_APACHE:80
    depends_on:
      - python
    links:
      - python
    restart: unless-stopped
volumes:
  mariadb_data:






